# Render deployment profile - Service Registry (Eureka)
server:
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    prefer-ip-address: false
    non-secure-port: ${SERVER_PORT:8761}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
